export const schemeRegionList = [
  { value: 'JABALPUR', label: 'JABALPUR' },
  { value: 'VARANASI', label: 'VARANASI' },
  { value: 'JALLANDHAR', label: 'JALLANDHAR' },
  { value: 'Udaipur', label: 'Udaipur' },
  { value: 'Pune', label: 'Pune' },
  { value: 'INDORE', label: 'INDORE' },
  { value: 'Surat', label: 'Surat' },
  { value: 'Agra', label: 'Agra' },
  { value: 'CHENNAI', label: 'CHENNAI' },
  { value: 'RAIPUR', label: 'RAIPUR' },
  { value: 'Madurai', label: 'Madurai' },
  { value: 'Raigarh', label: 'Raigarh' },
  { value: 'H.BAD', label: 'H.BAD' },
  { value: 'CUTTAK', label: 'CUTTAK' },
  { value: 'RANCHI', label: 'RANCHI' },
  { value: 'Siliguri', label: 'Siliguri' },
  { value: 'VIJAYWADA', label: 'VIJAYWADA' },
  { value: 'DELHI', label: 'DELHI' },
  { value: 'AHMEDABAD', label: 'AHMEDABAD' },
  { value: 'JODHPUR', label: 'JODHPUR' },
  { value: 'MEERUT', label: 'MEERUT' },
  { value: 'NAGPUR', label: 'NAGPUR' },
  { value: 'JAIPUR', label: 'JAIPUR' },
  { value: 'FARIDABAD', label: 'FARIDABAD' },
  { value: 'Calicut', label: 'Calicut' },
  { value: 'Cochin', label: 'Cochin' },
  { value: 'HUBLI', label: 'HUBLI' },
  { value: 'MUMBAI', label: 'MUMBAI' },
  { value: 'GUWAHATI', label: 'GUWAHATI' },
  { value: 'KOLKATTA', label: 'KOLKATTA' },
  { value: 'RAJKOT', label: 'RAJKOT' },
  { value: 'CHANDIGARH', label: 'CHANDIGARH' },
  { value: 'Patna', label: 'Patna' },
  { value: 'Coimbatore', label: 'Coimbatore' },
  { value: 'BNGLR', label: 'BNGLR' },
  { value: 'KANPUR', label: 'KANPUR' },
  { value: 'Nepal', label: 'Nepal' }
]

export const zoneList = [
  { value: 'NZ', label: 'North' },
  { value: 'EZ', label: 'East' },
  { value: 'SZ', label: 'South I' },
  { value: 'TZ', label: 'South II' },
  { value: 'WZ', label: 'West' },
  { value: 'CZ', label: 'Central' }
]


